# Generated by Django 4.2.1 on 2023-05-19 01:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("maximum_class_size", models.IntegerField()),
                ("credit_cost", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Enter the last name", max_length=32),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Enter the first name", max_length=32),
                ),
                (
                    "email",
                    models.EmailField(help_text="Enter the email", max_length=254),
                ),
                ("credits", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_and_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "class_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="roster.classtype",
                    ),
                ),
                ("roster", models.ManyToManyField(to="roster.client")),
            ],
            options={"ordering": ["-date_and_time"],},
        ),
    ]
